# ASSIGMENT NO # 1


  # Methods and Attributes  OF NUMPY


In [2]:
import numpy as np

In [3]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
np.empty((3,3))

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 5.95e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [5]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# list convert into array 
l=[1,2,3,4]
np.array(l)


array([1, 2, 3, 4])

In [9]:
#numpy range
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# numpy sum
a= np.array([19,7,3])
a.sum()

29

In [16]:
# sum of colume and rows
b=np.array([[1,9], [5,8]])
b.sum(axis=0)

array([ 6, 17])

In [17]:
b.sum(axis=1)

array([10, 13])

In [18]:
# Min and max term
c= np.array([9,6,3,1,5])
c.min()

1

In [19]:
c.max()

9

In [20]:
# index of min term
c.argmin()

3

In [21]:
# index of max term
c.argmax()

0

In [22]:
# logical operators
# OR operater
np.any([True,False,True])

True

In [23]:
#And operator
np.all([True,True,False])

False

In [26]:
d= np.zeros((100,100))
np.any(d !=0)

False

In [27]:
np.all(d==d)

True

In [32]:
e =np.array([1,3,5,7])
f= np.array([2,4,6,8])
g = np.array([3,5,7,9])
((e <= f) & (f <= g)).all()

True

In [3]:
import numpy as np

In [4]:
h=np.array([1,2,3,4])
h.shape

(4,)

In [18]:
# Arthematic operations
a1 = np.array([[0,2,3],[1,4,6]])
a2 = np.array([[2,5,3],[8,0,3]])

In [17]:
#ADDITION
a1+a1

array([[ 0,  4,  6],
       [ 2,  8, 12]])

In [19]:
#multiplication
a1*a2

array([[ 0, 10,  9],
       [ 8,  0, 18]])

In [20]:
#subtraction
a1-a2

array([[-2, -3,  0],
       [-7,  4,  3]])

In [21]:
#division
a1/a2

E:\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.   , 0.4  , 1.   ],
       [0.125,   inf, 2.   ]])

In [22]:
1/a1

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 0.5       , 0.33333333],
       [1.        , 0.25      , 0.16666667]])

In [24]:
a1>0

array([[False,  True,  True],
       [ True,  True,  True]])

In [25]:
a1[a1>0]

array([2, 3, 1, 4, 6])

In [26]:
# indexing
arr1=np.array([2,6,8,3,0,-8])
arr1[3]

3

In [27]:
#bolean index
arr1[arr1>4]

array([6, 8])

In [28]:
#fancy indexing 
arr1[[3,4]]

array([3, 0])

In [29]:
#indexing by row and coloum 
arr2= np.random.randn(5,5)

In [30]:
arr2[3]

array([ 0.1150953 , -0.19374709,  0.5336282 ,  0.08273435,  1.07775765])

In [31]:
arr2[2][4]

0.2815805511921878

In [32]:
#sclicing 
arr1[1:5:2]

array([6, 3])

In [33]:
arr2[1:5:1]

array([[-0.08688728,  1.9329495 , -2.07938685, -0.36193952, -1.51134912],
       [ 0.41571248,  0.3843873 ,  0.72034721,  0.99482406,  0.28158055],
       [ 0.1150953 , -0.19374709,  0.5336282 ,  0.08273435,  1.07775765],
       [-0.2426435 ,  1.20147823,  0.69704425,  1.51006608,  1.32085035]])

In [34]:
arr2[::,1:3]

array([[ 1.57524938,  0.51983333],
       [ 1.9329495 , -2.07938685],
       [ 0.3843873 ,  0.72034721],
       [-0.19374709,  0.5336282 ],
       [ 1.20147823,  0.69704425]])

In [37]:
arr3= np.ones((10,10))
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
arr3[1:-1,1:-1]=0
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
np.sqrt(arr2)

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[       nan, 1.25508939, 0.72099468, 1.12287482,        nan],
       [       nan, 1.39030554,        nan,        nan,        nan],
       [0.64475769, 0.61998976, 0.84873271, 0.99740867, 0.53064164],
       [0.33925698,        nan, 0.7304986 , 0.2876358 , 1.03815108],
       [       nan, 1.09611962, 0.83489176, 1.22884746, 1.14928254]])

In [44]:
#numpy where function
marks = np.array([45,80,90,78,34,67])
np.where(marks >= 45, "pass" ," fail")

array(['pass', 'pass', 'pass', 'pass', ' fail', 'pass'], dtype='<U5')

In [45]:
import numpy as np

In [49]:
arr5= np.array([1,3,5,6,7,8])
arr6= np.array([[2,34],[7,8]])

In [47]:
# no of dimensions
arr5.ndim

1

In [51]:
# shape is no of elements in array
arr5.shape


(6,)

In [52]:
arr6.shape

(2, 2)

In [53]:
#size give the info about rows and coloums
arr6.size

4

In [55]:
#data type
arr5.dtype

dtype('int32')

In [56]:
# Size of item
arr6.itemsize

4

In [59]:
#bit of array
arr6.nbytes

16

In [61]:
arr6.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False